/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.andercabrera.vistaAdmin;

import org.andercabrera.modelo.Vuelo;
import java.awt.Color;
import java.util.ArrayList;
import java.util.LinkedList;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deran
 */
public class VerVuelos extends javax.swing.JFrame {
    Vuelo vuelo = Vuelo.getInstance();

    /**
     * Creates new form VerVuelos
     */
    public VerVuelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        headerTxt = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        origenTxt = new javax.swing.JLabel();
        origenTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        destinoTxt = new javax.swing.JLabel();
        destinoTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        aerolineaTxt = new javax.swing.JLabel();
        aerolineaTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        claseTxt = new javax.swing.JLabel();
        claseTextField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        numeroPasajerosTxt = new javax.swing.JLabel();
        numeroPasajerosTextField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        precioTxt = new javax.swing.JLabel();
        precioTextField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        idTxt = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVuelos = new javax.swing.JTable();
        agregarBtn = new javax.swing.JButton();
        actualizarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        eliminarTodoBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        headerTxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        headerTxt.setForeground(new java.awt.Color(255, 255, 255));
        headerTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerTxt.setText("Vuelos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(headerTxt, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(headerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        origenTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        origenTxt.setForeground(new java.awt.Color(255, 255, 255));
        origenTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        origenTxt.setText("Origen");

        origenTextField.setBackground(new java.awt.Color(255, 255, 255));
        origenTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(origenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 219,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(origenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(origenTxt, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(origenTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26,
                                        Short.MAX_VALUE)
                                .addContainerGap()));

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));

        destinoTxt.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        destinoTxt.setForeground(new java.awt.Color(255, 255, 255));
        destinoTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        destinoTxt.setText("Destino");

        destinoTextField.setBackground(new java.awt.Color(255, 255, 255));
        destinoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(destinoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(destinoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(destinoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26,
                                        Short.MAX_VALUE)
                                .addContainerGap())
                        .addComponent(destinoTxt, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        jPanel5.setBackground(new java.awt.Color(255, 153, 0));

        aerolineaTxt.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        aerolineaTxt.setForeground(new java.awt.Color(255, 255, 255));
        aerolineaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aerolineaTxt.setText("Aerolinea");

        aerolineaTextField.setBackground(new java.awt.Color(255, 255, 255));
        aerolineaTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(aerolineaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(aerolineaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(aerolineaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(aerolineaTextField)
                                .addContainerGap()));

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));

        claseTxt.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        claseTxt.setForeground(new java.awt.Color(255, 255, 255));
        claseTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        claseTxt.setText("Clase");

        claseTextField.setBackground(new java.awt.Color(255, 255, 255));
        claseTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(claseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(claseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(claseTxt, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(claseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addContainerGap()));

        jPanel7.setBackground(new java.awt.Color(255, 153, 0));

        numeroPasajerosTxt.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        numeroPasajerosTxt.setForeground(new java.awt.Color(255, 255, 255));
        numeroPasajerosTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroPasajerosTxt.setText("No. Pasajeros");

        numeroPasajerosTextField.setBackground(new java.awt.Color(255, 255, 255));
        numeroPasajerosTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(numeroPasajerosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 214,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numeroPasajerosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)));
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(numeroPasajerosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(numeroPasajerosTextField)
                                .addContainerGap()));

        jPanel8.setBackground(new java.awt.Color(255, 153, 0));

        precioTxt.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        precioTxt.setForeground(new java.awt.Color(255, 255, 255));
        precioTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precioTxt.setText("Precio");

        precioTextField.setBackground(new java.awt.Color(255, 255, 255));
        precioTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(precioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 217,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(precioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)));
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(precioTxt, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(precioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26,
                                        Short.MAX_VALUE)
                                .addContainerGap()));

        jPanel9.setBackground(new java.awt.Color(255, 153, 0));

        idTxt.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        idTxt.setForeground(new java.awt.Color(255, 255, 255));
        idTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idTxt.setText("Id");

        idTextField.setBackground(new java.awt.Color(255, 255, 255));
        idTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 216,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)));
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(idTextField)
                                .addContainerGap()));

        jPanel10.setBackground(new java.awt.Color(255, 51, 51));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Regresar");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE));
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE));

        tablaVuelos.setBackground(new java.awt.Color(255, 255, 255));
        tablaVuelos.setForeground(new java.awt.Color(0, 0, 0));
        tablaVuelos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Id", "Origen", "Destino", "Aerolinea", "Clase", "Precio", "No. Pasajeros"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tablaVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVuelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVuelos);

        agregarBtn.setBackground(new java.awt.Color(0, 153, 0));
        agregarBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        agregarBtn.setForeground(new java.awt.Color(255, 255, 255));
        agregarBtn.setText("Agregar");
        agregarBtn.setBorder(null);
        agregarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarBtnMouseClicked(evt);
            }
        });
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        actualizarBtn.setBackground(new java.awt.Color(0, 204, 51));
        actualizarBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        actualizarBtn.setForeground(new java.awt.Color(255, 255, 255));
        actualizarBtn.setText("Actualizar");
        actualizarBtn.setBorder(null);
        actualizarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarBtnMouseClicked(evt);
            }
        });
        actualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBtnActionPerformed(evt);
            }
        });

        eliminarBtn.setBackground(new java.awt.Color(255, 51, 51));
        eliminarBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        eliminarBtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarBtn.setText("Eliminar");
        eliminarBtn.setBorder(null);
        eliminarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarBtnMouseClicked(evt);
            }
        });

        eliminarTodoBtn.setBackground(new java.awt.Color(255, 51, 51));
        eliminarTodoBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        eliminarTodoBtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarTodoBtn.setText("Eliminar todo");
        eliminarTodoBtn.setBorder(null);
        eliminarTodoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarTodoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarTodoBtnMouseClicked(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Mostrar datos");
        jButton2.setToolTipText("");
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap(234, Short.MAX_VALUE)
                                                .addComponent(eliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21)
                                                .addComponent(eliminarTodoBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(jPanel9,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel7,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel8,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel6,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                                Short.MAX_VALUE)
                                                        .addComponent(jPanel5,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                                Short.MAX_VALUE)
                                                        .addComponent(jPanel3,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jPanel4,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                jPanel1Layout.createSequentialGroup()
                                                                        .addGap(14, 14, 14)
                                                                        .addComponent(agregarBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                85,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(actualizarBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                85,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(56, 56, 56)
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(actualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(eliminarBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(eliminarTodoBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton1))
                                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(28, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaVuelosMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tablaVuelosMouseClicked
        // TODO add your handling code here:
        int fila = tablaVuelos.getSelectedRow();
        if (fila >= 0) {
            idTextField.setText(tablaVuelos.getValueAt(fila, 0).toString());
            origenTextField.setText(tablaVuelos.getValueAt(fila, 1).toString());
            destinoTextField.setText(tablaVuelos.getValueAt(fila, 2).toString());
            aerolineaTextField.setText(tablaVuelos.getValueAt(fila, 3).toString());
            claseTextField.setText(tablaVuelos.getValueAt(fila, 4).toString());
            precioTextField.setText(tablaVuelos.getValueAt(fila, 5).toString());
            numeroPasajerosTextField.setText(tablaVuelos.getValueAt(fila, 6).toString());
        }
    }// GEN-LAST:event_tablaVuelosMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tablaVuelos.getModel();
        Object[] fila = new Object[7];
        for (int i = 0; i < vuelo.getListaVuelos().size(); i++) {
            fila[0] = vuelo.getListaVuelos().get(i).getId();
            fila[1] = vuelo.getListaVuelos().get(i).getOrigen();
            fila[2] = vuelo.getListaVuelos().get(i).getDestino();
            fila[3] = vuelo.getListaVuelos().get(i).getAerolinea();
            fila[4] = vuelo.getListaVuelos().get(i).getClase();
            fila[5] = vuelo.getListaVuelos().get(i).getPrecio();
            fila[6] = vuelo.getListaVuelos().get(i).getNumeroPasajeros();
            modelo.addRow(fila);
        } // GEN-LAST:event_jButton2MouseClicked
    }

    private void eliminarBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_eliminarBtnMouseClicked
        // TODO add your handling code here:
        // select de jtable
        DefaultTableModel modelo = (DefaultTableModel) tablaVuelos.getModel();
        int fila = tablaVuelos.getSelectedRow();
        if (fila >= 0) {
            modelo.removeRow(fila);
            vuelo.getListaVuelos().remove(fila);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }
    }// GEN-LAST:event_eliminarBtnMouseClicked

    private void eliminarTodoBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_eliminarTodoBtnMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tablaVuelos.getModel();
        int filas = tablaVuelos.getRowCount();

        for (int i = filas - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }

        vuelo.getListaVuelos().clear();
    }// GEN-LAST:event_eliminarTodoBtnMouseClicked

    private void columnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_columnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_columnActionPerformed

    private void actualizarBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_actualizarBtnMouseClicked
        // TODO add your handling code here:
        int i = tablaVuelos.getSelectedRow();
        if (i >= 0) {
            tablaVuelos.setValueAt(idTextField.getText(), i, 0);
            tablaVuelos.setValueAt(origenTextField.getText(), i, 1);
            tablaVuelos.setValueAt(destinoTextField.getText(), i, 2);
            tablaVuelos.setValueAt(aerolineaTextField.getText(), i, 3);
            tablaVuelos.setValueAt(claseTextField.getText(), i, 4);
            tablaVuelos.setValueAt(precioTextField.getText(), i, 5);
            tablaVuelos.setValueAt(numeroPasajerosTextField.getText(), i, 6);
            // update in the arraylist
            vuelo.getListaVuelos().get(i).setId(Integer.parseInt(idTextField.getText()));
            vuelo.getListaVuelos().get(i).setOrigen(origenTextField.getText());
            vuelo.getListaVuelos().get(i).setDestino(destinoTextField.getText());
            vuelo.getListaVuelos().get(i).setAerolinea(aerolineaTextField.getText());
            vuelo.getListaVuelos().get(i).setClase(claseTextField.getText());
            vuelo.getListaVuelos().get(i).setPrecio(Integer.parseInt(precioTextField.getText()));
            vuelo.getListaVuelos().get(i).setNumeroPasajeros(Integer.parseInt(numeroPasajerosTextField.getText()));
            //reset the textfields
            idTextField.setText("");
            origenTextField.setText("");
            destinoTextField.setText("");
            aerolineaTextField.setText("");
            claseTextField.setText("");
            precioTextField.setText("");
            numeroPasajerosTextField.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }

    }// GEN-LAST:event_actualizarBtnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        test regresar = new test();
        this.setVisible(false);
        regresar.setVisible(true);
    }// GEN-LAST:event_jButton1MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel9MouseClicked
        MenuAdmin menuAdmin = new MenuAdmin();
        this.setVisible(false);
        menuAdmin.setVisible(true);
    }// GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel9MousePressed
        jLabel9.setForeground(Color.gray);
    }// GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel9MouseReleased
        jLabel9.setForeground(Color.white);
    }// GEN-LAST:event_jLabel9MouseReleased

    private void actualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_actualizarBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_actualizarBtnActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_agregarBtnActionPerformed

    }// GEN-LAST:event_agregarBtnActionPerformed

    private void agregarBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_agregarBtnMouseClicked
        // TODO add your handling code here:
        Vuelo item = new Vuelo(
                origenTextField.getText(),
                destinoTextField.getText(),
                aerolineaTextField.getText(), claseTextField.getText(),
                Integer.parseInt(idTextField.getText()),
                Integer.parseInt(precioTextField.getText()),
                Integer.parseInt(numeroPasajerosTextField.getText()));

        if (idTextField.getText().isEmpty() || origenTextField.getText().isEmpty()
                || destinoTextField.getText().isEmpty() || aerolineaTextField.getText().isEmpty()
                || claseTextField.getText().isEmpty() || precioTextField.getText().isEmpty()
                || numeroPasajerosTextField.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Faltan datos por llenar");
        } else {
            DefaultTableModel model = (DefaultTableModel) tablaVuelos.getModel();
            model.addRow(new Object[] { item.getId(), item.getOrigen(), item.getDestino(), item.getAerolinea(),
                    item.getClase(), item.getPrecio(), item.getNumeroPasajeros() });
            vuelo.getListaVuelos().add(item);
            // reset the textfields
            origenTextField.setText("");
            destinoTextField.setText("");
            aerolineaTextField.setText("");
            claseTextField.setText("");
            precioTextField.setText("");
            numeroPasajerosTextField.setText("");
            idTextField.setText("");
            // simple test to show the data in the arraylist
            for (int i = 0; i < vuelo.getListaVuelos().size(); i++) {
                System.out.println("---------------------------");
                System.out.println(vuelo.getListaVuelos().get(i).getId());
                System.out.println(vuelo.getListaVuelos().get(i).getOrigen());
                System.out.println(vuelo.getListaVuelos().get(i).getDestino());
                System.out.println(vuelo.getListaVuelos().get(i).getAerolinea());
                System.out.println(vuelo.getListaVuelos().get(i).getClase());
                System.out.println(vuelo.getListaVuelos().get(i).getPrecio());
                System.out.println(vuelo.getListaVuelos().get(i).getNumeroPasajeros());
                System.out.println("---------------------------\n");
            }
            // ? vuelo.setListaVuelos(vuelo.getListaVuelos());
        }

    }// GEN-LAST:event_agregarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBtn;
    private javax.swing.JTextField aerolineaTextField;
    private javax.swing.JLabel aerolineaTxt;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JTextField claseTextField;
    private javax.swing.JLabel claseTxt;
    private javax.swing.JTextField destinoTextField;
    private javax.swing.JLabel destinoTxt;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JButton eliminarTodoBtn;
    private javax.swing.JLabel headerTxt;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel idTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numeroPasajerosTextField;
    private javax.swing.JLabel numeroPasajerosTxt;
    private javax.swing.JTextField origenTextField;
    private javax.swing.JLabel origenTxt;
    private javax.swing.JTextField precioTextField;
    private javax.swing.JLabel precioTxt;
    private javax.swing.JTable tablaVuelos;
    // End of variables declaration//GEN-END:variables
}
